#!/bin/bash

g++ -o Div_alice Div_alice.c -ltfhe-spqlios-avx -std=c++11
g++ -o Div_cloud Div_cloud.c -ltfhe-spqlios-avx -std=c++11
g++ -o Div_verif Div_verif.c -ltfhe-spqlios-avx -std=c++11

chmod 755 Div_alice
chmod 755 Div_cloud
chmod 755 Div_verif

./Div_alice
./Div_cloud
./Div_verif
