#!/bin/bash

g++ -o Multi_alice Multi_alice.c -ltfhe-spqlios-fma -std=c++11
g++ -o Multi_cloud Multi_cloud.c -ltfhe-spqlios-fma -std=c++11
g++ -o Multi_verif Multi_verif.c -ltfhe-spqlios-fma -std=c++11

chmod 777 Multi_alice
chmod 777 Multi_cloud
chmod 777 Multi_verif

./Multi_alice
./Multi_cloud
./Multi_verif
