#!/bin/bash

g++ -o Multi_alice Multi_alice.c -ltfhe-spqlios-avx -std=c++11
#g++ -o MPI_Multiworking MPI_Multiworking.c -ltfhe-spqlios-avx -std=c++11
mpicc MPI_Multiworking.c -o MPI_Multiworking -ltfhe-spqlios-avx
#g++ -o MPI_Multi MPI_Multi.c  -ltfhe-spqlios-fma -std=c++11
g++ -o MPI_verifworking MPI_verifworking.c -ltfhe-spqlios-avx -std=c++11

chmod 777 Multi_alice
chmod 777 Multi_cloud


./Multi_alice
mpirun -np 4 ./MPI_Multiworking
./MPI_verifworking
