#!/bin/bash

g++ -o Sub_alice Sub_alice.c -ltfhe-spqlios-avx -std=c++11
g++ -o Sub_cloud Sub_cloud.c -ltfhe-spqlios-avx -std=c++11
g++ -o Sub_verif Sub_verif.c -ltfhe-spqlios-avx -std=c++11

chmod 755 Sub_alice
chmod 755 Sub_cloud
chmod 755 Sub_verif

./Sub_alice
./Sub_cloud
./Sub_verif
